import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiTwotoneMail,
} from "react-icons/ai";
import Image from "next/image";
import kene from "../public/kene.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.jpeg";
import web2 from "../public/web2.jpeg";
import web3 from "../public/web3.jpeg";
import web4 from "../public/web4.jpeg";
import { useState } from "react";

{
  /* <img
                src="https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E"
                alt=""
              /> */
}

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [showModal, setShowModal] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kenechukwu Ubesie |Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          {/* Navigation Bar */}

          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">Kenechukwu</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <button
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  type="button"
                  onClick={() => setShowModal(true)}
                >
                  Ask Me
                </button>
              </li>
            </ul>
          </nav>

          {/* Modal */}

          {showModal ? (
            <>
              <div className="justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none">
                <div className="relative w-auto my-6 mx-auto max-w-3xl">
                  {/*content*/}
                  <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none">
                    {/*header*/}
                    <div className="flex items-start justify-between p-5 border-b border-solid border-slate-200 rounded-t">
                      <h3 className="text-3xl font-semibold">
                        Make Your Enquiries
                      </h3>
                    </div>
                    {/*body Form*/}
                    <div className="relative p-6 flex-auto">
                      <form class="w-full max-w-sm">
                        {/* Full Name */}
                        <div class="md:flex md:items-center mb-6">
                          <div class="md:w-1/3">
                            <label
                              class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                              for="inline-full-name"
                            >
                              Full Name
                            </label>
                          </div>
                          <div class="md:w-2/3">
                            <input
                              class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                              id="inline-full-name"
                              type="text"
                              placeholder="Jane Doe"
                            />
                          </div>
                        </div>
                        {/* Phone NUmber  */}
                        <div class="md:flex md:items-center mb-6">
                          <div class="md:w-1/3">
                            <label
                              class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                              for="phone"
                            >
                              Phone Number
                            </label>
                          </div>
                          <div class="md:w-2/3">
                            <input
                              class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                              id="phone"
                              type="tel"
                              placeholder="+1234567890"
                            />
                          </div>
                        </div>

                        {/* Email  */}
                        <div class="md:flex md:items-center mb-6">
                          <div class="md:w-1/3">
                            <label
                              class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                              for="email"
                            >
                              Email Address
                            </label>
                          </div>
                          <div class="md:w-2/3">
                            <input
                              class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                              id="email"
                              type="email"
                              placeholder="janedoe@example.com"
                            />
                          </div>
                        </div>

                        {/* Inquiry Text */}
                        <div class="mb-6">
                          <label
                            for="large-input"
                            class="block mb-2 text-sm font-medium text-gray-500 dark:text-gray-300"
                          >
                            Your Message
                          </label>
                          <input
                            type="text"
                            id="large-input"
                            class="block p-4 w-full text-gray-700 bg-gray-200 rounded-lg border border-gray-300 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-200 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                          />
                        </div>

                        {/* Submit button  */}
                        <div class="md:flex md:items-center">
                          <div class="md:w-1/3"></div>
                          <div class="md:w-2/3">
                            <button
                              class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded"
                              type="button"
                            >
                              Submit
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                    {/*footer*/}
                    <div className="flex items-center justify-end p-6 border-t border-solid border-slate-200 rounded-b">
                      <button
                        className="text-red-500 background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                        type="button"
                        onClick={() => setShowModal(false)}
                      >
                        Close
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
            </>
          ) : null}

          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl text-center hover:-translate-y-1 hover:scale-80 duration-300">
              Kene Ubesie
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white hover:-translate-y-1 hover:scale-80 duration-300">
              Full Stack Developer and Graphics Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">
              FullStack Web Developer offering services for coding and graphics
              design requirements. Feel free to get in touch with me about your
              projects.
            </p>
          </div>

          {/* social media icons */}
          <div className="text-5xl flex justify-center gap-8 md:gap-16 py-3 text-gray-600">
            <a href="https://linkedin.com/in/kene-ubesie" target={"_blank"}>
              <AiFillLinkedin className="dark:text-gray-400" />
            </a>
            <a href="https://github.com/Kenechvkwv" target={"_blank"}>
              <AiFillGithub className="dark:text-gray-400" />
            </a>
            <a href="https://twitter.com/Kenechvkwv" target={"_blank"}>
              <AiFillTwitterCircle className="dark:text-gray-400" />
            </a>
            <AiTwotoneMail className="dark:text-gray-400" />
          </div>

          {/* Cartoon Image */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 animate-bounce">
            <Image src={kene} fill object-fit="cover" />
          </div>
        </section>

        {/* My Services */}

        <section>
          <div>
            <h3 className="text-3xl py-1 font-semibold dark:text-gray-200 hover:-translate-y-1 hover:scale-80 duration-300">
              Services I offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Since I first started working in the tech sector, I have worked
              and provided consulting services both locally and remotely for{" "}
              <span className="text-teal-500">individuals</span>,
              <span className="text-teal-500">startups</span>, and worked in
              professional teams to develop web products for both commercial and
              consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              I provide a variety of services, such as designing, teaching, and
              programming.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg  p-10 rounded-xl my-10 justify-center  dark:shadow-gray-600 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                className=" m-auto"
                src={design}
                width={100}
                height={100}
                alt=""
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-200">
                Beautiful Graphic Designs
              </h3>
              <p className="py-2 dark:text-gray-400">
                Creating stunning graphic materials that meet your demands while
                adhering to fundamental design principles.
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-gray-600 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image className=" m-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-200">
                Web Development
              </h3>
              <p className="py-2 dark:text-gray-400">
                Designing impressive user interfaces for your website's front
                end and highly legible, high quality back end layouts for your
                completely optimized websites.
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-gray-600 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                className=" m-auto"
                src={consulting}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-200">
                Teaching
              </h3>
              <p className="py-2 dark:text-gray-400">
                I am capable of effectively tutoring and guiding beginners in
                web development from a beginner to a professional level by
                employing teaching strategies tailored specifically for each
                student.
              </p>
            </div>
          </div>
        </section>

        {/* Portfolio Section */}
        <section>
          <div>
            <h3 className="text-3xl py-1 font-semibold dark:text-gray-200">
              PortFolio
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              I am a fullstack Software Engineer with 2+ years of experience in
              the implementation of data driven web applications. I have
              experience with all stages of the software development cycle, and
              adequate knowledge of languages/technologies such as PHP,
              JavaScript, React, MySQL, HTML, CSS etc. I also have experience
              with frameworks such as Bootstrap, MaterializeCss, TailwindCss and
              Next.JS. I have experience with tools such as Git amongst others.
              I am passionate about software development. I am a fast learner
              and take pride in my ability to quickly master and apply new
              knowledge.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              My objective is to join a team of very skilled and driven
              engineers that can inspire me to work and achieve beyond my
              current perceived limits, while contributing to a meaningful
              project and taking my career to the next level.
            </p>
            <hr />
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              The projects I have recently been able to work on are listed
              below.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap justify-center">
            <div className="basis-1/3 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
