import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedIn,
  AiFillYoutube,
} from "react-icons";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kenechukwu Ubesie |Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 ">
        <section className="min-h-screen">
          {/* Navigation Bar */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Kene</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="curor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div>
            <h2>Kenechukwu Ubesie</h2>
            <h3>Developer and Designer</h3>
            <p>
              FullStack Web Developer providing services for programming and
              design content needs. Feel free to contact me for your projects.
            </p>
          </div>

          <div></div>
        </section>
      </main>
    </div>
  );
}
